# Generated by Django 3.2.2 on 2021-05-09 18:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('earthquake_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geography', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('datetime', models.DateTimeField()),
                ('place', models.CharField(max_length=128)),
                ('mag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('public_datetime', models.DateTimeField()),
                ('article_content', models.TextField()),
                ('url', models.TextField()),
                ('fk_earthquake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_gis.earthquake')),
            ],
        ),
    ]
